### ISSUE TITLE
Running as user fails, permission denied in /root/

### ISSUE THREAD

**Issue by divadsn** [ComboStrap/dokuwiki-docker#1]
I get the following error when trying to run this as an user:

```
/opt/dokuwiki-docker/bin/dokuwiki-docker-entrypoint: line 25: /root/.bashrc: Permission denied
```

docker-compose.yml:

```
services:
  dokuwiki-test:
    image: ghcr.io/combostrap/dokuwiki:php8.3-v1
    restart: unless-stopped
    user: 1000:1000
    environment:
      - TZ=${TZ}
      - PHP_TIMEZONE=${TZ}
    volumes:
      - ./wiki:/storage
```
